In [115]:
!pip install --user trl

  Using cached trl-0.7.4-py3-none-any.whl.metadata (10 kB)
Using cached trl-0.7.4-py3-none-any.whl (133 kB)
DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [5]:
import torch
import torch.nn.functional as F

In [7]:
a = torch.randn(1, 4, requires_grad=True)

In [8]:
a

tensor([[ 0.2511, -0.2847, -1.3987,  0.9078]], requires_grad=True)

In [9]:
s = torch.argmax(a)

In [10]:
s

tensor(3)

In [19]:
weights = torch.tensor([0, 10, 3, 0], dtype=torch.float, requires_grad=True) # create a tensor of weights
weights

tensor([ 0., 10.,  3.,  0.], requires_grad=True)

In [20]:
s = torch.multinomial(weights, 1)

In [21]:
s

tensor([2])

In [22]:
s.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [226]:
import torch
from transformers import AutoTokenizer, GPT2LMHeadModel


torch.manual_seed(12046)

tokenizer = AutoTokenizer.from_pretrained("gpt2")

In [227]:
tokenizer.vocab_size

50257

In [231]:
import math

math.pow(50256, 10)

1.027730370438185e+47

In [55]:
res = model.generate(**ids, max_length=1)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Input length of input_ids is 7, but `max_length` is set to 1. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.


In [56]:
res

tensor([[2061,  318,  262, 3139,  286, 2807,   30,  198]])

In [53]:
l = model(**ids).logits

In [54]:
l

tensor([[[ -37.2172,  -36.8864,  -40.3563,  ...,  -43.4351,  -43.0232,
           -37.0993],
         [ -84.7418,  -82.6453,  -88.2857,  ...,  -89.4501,  -90.0555,
           -84.6770],
         [ -94.2372,  -92.2747,  -95.0347,  ...,  -94.9362,  -97.9820,
           -91.8550],
         ...,
         [ -75.3586,  -73.5543,  -77.7737,  ...,  -80.5165,  -81.9881,
           -76.4165],
         [ -77.2812,  -75.8471,  -80.8869,  ...,  -88.2672,  -86.0258,
           -79.5727],
         [-123.9086, -123.2837, -124.5704,  ..., -135.1090, -134.9653,
          -119.7716]]], grad_fn=<UnsafeViewBackward0>)

In [60]:
with torch.no_grad():
    ll = model(**ids).logits
ll

tensor([[[ -37.2172,  -36.8864,  -40.3563,  ...,  -43.4351,  -43.0232,
           -37.0993],
         [ -84.7418,  -82.6453,  -88.2857,  ...,  -89.4501,  -90.0555,
           -84.6770],
         [ -94.2372,  -92.2747,  -95.0347,  ...,  -94.9362,  -97.9820,
           -91.8550],
         ...,
         [ -75.3586,  -73.5543,  -77.7737,  ...,  -80.5165,  -81.9881,
           -76.4165],
         [ -77.2812,  -75.8471,  -80.8869,  ...,  -88.2672,  -86.0258,
           -79.5727],
         [-123.9086, -123.2837, -124.5704,  ..., -135.1090, -134.9653,
          -119.7716]]])

In [87]:
weights = torch.tensor([0, 10, 3, 0], dtype=torch.float, requires_grad=True)

In [88]:
y = torch.multinomial(weights, 1)
y

tensor([1])

In [89]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [91]:
F.softmax(weights)[y]

<ipython-input-91-26e670d9452d>:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(weights)[y]


tensor([0.9990], grad_fn=<IndexBackward0>)

In [82]:
y

tensor([2])

In [86]:
k = (weights == weights[y]).nonzero()

In [51]:
ids['input_ids'].requires_grad=True

RuntimeError: only Tensors of floating point and complex dtype can require gradients

torch.Tensor

In [50]:
type(a)

torch.Tensor

In [57]:
a = torch.rand(1, 4)
a.requires_grad=True
y = torch.sum(a)
y

tensor(1.0545, grad_fn=<SumBackward0>)

In [46]:
torch.sum(a).backward()

In [37]:
y = torch.sum(ids['input_ids'])
y

tensor(8903)

In [38]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [94]:
x = torch.randn(3, 2, requires_grad=True)
y = torch.ones(3, 2)
x
z = torch.where(x > 0, 1.0, 0.0)

In [95]:
z

tensor([[0., 1.],
        [1., 1.],
        [0., 0.]])

In [103]:
t = (x - 0 > 0.001) * 1 + 0

In [100]:
x

tensor([[-1.4747,  0.2449],
        [ 0.8045,  0.4111],
        [-0.7769, -0.4431]], requires_grad=True)

In [104]:
t

tensor([[0, 1],
        [1, 1],
        [0, 0]])

In [106]:
(x - 0 > 0.001)

tensor([[False,  True],
        [ True,  True],
        [False, False]])

In [108]:
x

tensor([[-1.4747,  0.2449],
        [ 0.8045,  0.4111],
        [-0.7769, -0.4431]], requires_grad=True)

In [109]:
torch.max(x)

tensor(0.8045, grad_fn=<MaxBackward1>)

In [117]:
from trl import AutoModelForCausalLMWithValueHea

ModuleNotFoundError: No module named 'trl'

In [1]:
import trl

/Users/tgbaggio/.local/lib/python3.8/site-packages/trl/trainer/ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(


In [2]:
from trl import AutoModelForCausalLMWithValueHead

In [4]:
model = AutoModelForCausalLMWithValueHead.from_pretrained('lvwerra/gpt2-imdb')

In [5]:
model

AutoModelForCausalLMWithValueHead(
  (pretrained_model): GPT2LMHeadModel(
    (transformer): GPT2Model(
      (wte): Embedding(50257, 768)
      (wpe): Embedding(1024, 768)
      (drop): Dropout(p=0.1, inplace=False)
      (h): ModuleList(
        (0-11): 12 x GPT2Block(
          (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (attn): GPT2Attention(
            (c_attn): Conv1D()
            (c_proj): Conv1D()
            (attn_dropout): Dropout(p=0.1, inplace=False)
            (resid_dropout): Dropout(p=0.1, inplace=False)
          )
          (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (mlp): GPT2MLP(
            (c_fc): Conv1D()
            (c_proj): Conv1D()
            (act): NewGELUActivation()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (lm_head): Linear(in_features=768, out_features=50257, bias=False)
  )
  (

In [10]:
l = model(**ids)

In [13]:
l[0].shape

torch.Size([1, 7, 50257])

In [15]:
l[2].shape

torch.Size([1, 7])

In [16]:
from transformers import AutoTokenizer, pipeline

In [17]:
p = pipeline('sentiment-analysis', 'lvwerra/distilbert-imdb')

Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


In [21]:
sent_kwargs = {"return_all_scores": True, "function_to_apply": "none", "batch_size": 16}

In [29]:
question = 'What is the capital of China?'
ids = tokenizer(question, return_tensors="pt")
ids

{'input_ids': tensor([[2061,  318,  262, 3139,  286, 2807,   30]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}

In [30]:
pipe_outputs = p(question, **sent_kwargs)

In [31]:
pipe_outputs

[[{'label': 'NEGATIVE', 'score': 0.28462526202201843},
  {'label': 'POSITIVE', 'score': -0.498414009809494}]]

In [32]:
score = torch.randn(3)
log = torch.randn(3, 7)

In [45]:
for s, l in zip(score, log):
    print(s, l.shape)

tensor(2.3532) torch.Size([7])
tensor(-0.3089) torch.Size([7])
tensor(-1.0061) torch.Size([7])


In [46]:
x = torch.randn(4)

In [47]:
x

tensor([ 0.8624,  0.1586, -1.3384,  0.4741])

In [48]:
x += 1

In [49]:
x

tensor([ 1.8624,  1.1586, -0.3384,  1.4741])

In [51]:
x[2] += 1

In [55]:
x = torch.randn(3, 4)
x

tensor([[-0.0498,  0.3148, -0.6248,  0.0660],
        [ 1.1840, -1.0514, -0.8765, -0.0313],
        [ 2.3417, -0.0704, -0.0996,  1.7966]])

In [56]:
x[::-1]

ValueError: step must be greater than zero

In [79]:
self_config_gamma = 0.8
self_config_lam = 0.9

def compute_advantages(
    values: torch.FloatTensor,
    rewards: torch.FloatTensor):
    lastgaelam = 0
    advantages_reversed = []
    gen_len = rewards.shape[-1]
    for t in reversed(range(gen_len)):
        nextvalues = values[:, t + 1] if t < gen_len - 1 else 0.0
        delta = rewards[:, t] + self_config_gamma * nextvalues - values[:, t]
        lastgaelam = delta + self_config_gamma * self_config_lam * lastgaelam
        advantages_reversed.append(lastgaelam)
    advantages = torch.stack(advantages_reversed[::-1]).transpose(0, 1)

    returns = advantages + values
    advantages = advantages.detach()
    return values, advantages, returns


In [80]:
values = torch.tensor([[3., 4., 2.]])
rewards = torch.tensor([[-1., 2., 2.]])

In [81]:
compute_advantages(values, rewards)

(tensor([[3., 4., 2.]]),
 tensor([[-1.0880, -0.4000,  0.0000]]),
 tensor([[1.9120, 3.6000, 2.0000]]))

In [1]:
0.8 * 2 + 0.8 ** 2 * 2 - 1

1.8800000000000003

In [5]:
import gym
import pygame

env = gym.make('MountainCar-v0', render_mode="human")

In [6]:
# Observation and action space 
obs_space = env.observation_space
action_space = env.action_space
print("The observation space: {}".format(obs_space))
print("The action space: {}".format(action_space))

The observation space: Box([-1.2  -0.07], [0.6  0.07], (2,), float32)
The action space: Discrete(3)


In [7]:
import matplotlib.pyplot as plt 

# reset the environment and see the initial observation
obs = env.reset()
print("The initial observation is {}".format(obs))

# Sample a random action from the entire action space
random_action = env.action_space.sample()
print(random_action)

# # Take the action and get the new observation space
new_obs, reward, done, _, info = env.step(random_action)
env.render() 
pygame.display.update()
print("The new observation is {}".format(new_obs))

The initial observation is (array([-0.46305716,  0.        ], dtype=float32), {})
0
The new observation is [-0.46450874 -0.00145157]


In [16]:
# Sample a random action from the entire action space
random_action = env.action_space.sample()
print(random_action)

# # Take the action and get the new observation space
new_obs, reward, done, _, info = env.step(random_action)
print("The new observation is {}".format(new_obs))

2
The new observation is [-5.2235210e-01 -4.3133463e-04]


In [17]:
env.close()


In [19]:
import pygame

pygame.event.get

<function pygame.event.get>

In [1]:
import gymnasium as gym

env = gym.make("LunarLander-v2", render_mode="human")
observation, info = env.reset()

for _ in range(1000):
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()

env.close()

DependencyNotInstalled: Box2D is not installed, run `pip install gymnasium[box2d]`

In [2]:
import gymnasium as gym
import math
import random
import matplotlib
import matplotlib.pyplot as plt
env = gym.make("CartPole-v1")

# set up matplotlib
is_ipython = 'inline' in matplotlib.get_backend()
if is_ipython:
    from IPython import display

plt.ion()

In [52]:
import gymnasium as gym
import pygame

env = gym.make("CartPole-v1", render_mode="human")
observation, info = env.reset(seed=42)
#for _ in range(100):
#    action = env.action_space.sample()  # this is where you would insert your policy
#    observation, reward, terminated, truncated, info = env.step(action)
#    if terminated or truncated:
#        break
#env.close()

#pygame.display.update()

In [62]:
action = env.action_space.sample()  # this is where you would insert your policy
env.step(1)

(array([ 0.20159529,  1.9464185 , -0.22034578, -2.9908078 ], dtype=float32),
 1.0,
 True,
 False,
 {})

In [63]:
env.close()

In [64]:
0.3/4

0.075

In [163]:
m = [
    [0.775, 0.075, 0.075, 0.075],
    [0.075, 0.775, 0.075, 0.075],
    [0.075, 0.075, 0.775, 0.075],
    [0.075, 0.075, 0.075, 0.775]
]

In [164]:
import torch
m = torch.tensor(m)

In [95]:
m @ torch.ones(4, 1)

tensor([[1.],
        [1.],
        [1.],
        [1.]])

In [192]:
r = torch.tensor([[2.0, 1.0, -1.0, -2.0]]).T
v = torch.tensor([[200.0, 100.0, -100.0, -200.0]]).T
gamma = 0.9

In [198]:
for i in range(10):
    print(v)
    v = gamma * m @ v + r

tensor([[ 5.4054],
        [ 2.7027],
        [-2.7027],
        [-5.4054]])
tensor([[ 5.4054],
        [ 2.7027],
        [-2.7027],
        [-5.4054]])
tensor([[ 5.4054],
        [ 2.7027],
        [-2.7027],
        [-5.4054]])
tensor([[ 5.4054],
        [ 2.7027],
        [-2.7027],
        [-5.4054]])
tensor([[ 5.4054],
        [ 2.7027],
        [-2.7027],
        [-5.4054]])
tensor([[ 5.4054],
        [ 2.7027],
        [-2.7027],
        [-5.4054]])
tensor([[ 5.4054],
        [ 2.7027],
        [-2.7027],
        [-5.4054]])
tensor([[ 5.4054],
        [ 2.7027],
        [-2.7027],
        [-5.4054]])
tensor([[ 5.4054],
        [ 2.7027],
        [-2.7027],
        [-5.4054]])
tensor([[ 5.4054],
        [ 2.7027],
        [-2.7027],
        [-5.4054]])


In [142]:
m = [
    [0.5, 0.5, 0.0],
    [0.25, 0.5, 0.25],
    [0, 0.5, 0.5]
]

In [143]:
m = torch.tensor(m)

In [160]:
n = torch.tensor([[0.0, 0.9, 0.1]])

In [2]:
for i in range(10):
    print(n)
    n = n @ m
    
    


NameError: name 'n' is not defined

In [51]:
import torch
from torch.autograd import Variable

In [170]:
logits = torch.tensor([[1., 1., 1.]], requires_grad=True)
y = F.gumbel_softmax(logits, tau=1, hard=True)
(y * torch.arange(3)).sum().backward()
y, logits.grad

(tensor([[1., 0., 0.]], grad_fn=<AddBackward0>),
 tensor([[-0.2796,  0.1884,  0.0913]]))

In [148]:
y_soft = F.gumbel_softmax(logits, tau=1, hard=False)
y_soft.max(-1, keepdim=True)[1] - y_soft.detach() + y_soft

tensor([[1., 1.]], grad_fn=<AddBackward0>)

In [117]:
F.gumbel_softmax(logits, tau=1, hard=True)

tensor([[1., 0.]], grad_fn=<AddBackward0>)

In [81]:
def sample_gumbel(shape, eps=1e-20):
    U = torch.rand(shape)
    return -Variable(torch.log(-torch.log(U + eps) + eps))

def gumbel_softmax_sample(logits, temperature):
    y = logits + sample_gumbel(logits.size())
    return F.softmax(y / temperature, dim=-1)

def gumbel_softmax(logits, temperature):
    """
    ST-gumple-softmax
    input: [*, n_class]
    return: flatten --> [*, n_class] an one-hot vector
    """
    y = gumbel_softmax_sample(logits, temperature)
    shape = y.size()
    _, ind = y.max(dim=-1)
    y_hard = torch.zeros_like(y).view(-1, shape[-1])
    y_hard.scatter_(1, ind.view(-1, 1), 1)
    y_hard = y_hard.view(*shape)
    y_hard = (y_hard - y).detach() + y
    return y_hard.view(-1,latent_dim*categorical_dim), y, ind

In [53]:
gumbel_softmax(torch.randn(4, 3), 0.1)

NameError: name 'latent_dim' is not defined

In [55]:
latent_dim = 10
categorical_dim = 3
x = torch.randn(5, latent_dim, categorical_dim)

In [85]:
x.requires_grad=True

In [86]:
y, k, ind = gumbel_softmax(x, 0.1)

In [87]:
ind

tensor([[1, 2, 2, 2, 2, 0, 2, 1, 2, 1],
        [0, 2, 0, 0, 2, 1, 0, 0, 0, 0],
        [0, 0, 2, 1, 1, 1, 1, 0, 0, 0],
        [1, 2, 1, 2, 0, 1, 1, 1, 0, 0],
        [2, 0, 0, 1, 0, 2, 0, 1, 0, 1]])

In [89]:
k.max(dim=-1)

torch.return_types.max(
values=tensor([[0.5745, 1.0000, 0.9985, 1.0000, 1.0000, 0.5934, 1.0000, 0.8247, 1.0000,
         0.9999],
        [0.7558, 1.0000, 0.9999, 1.0000, 1.0000, 0.5294, 0.9994, 0.8727, 0.9999,
         0.9213],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.9942, 1.0000, 0.9996, 1.0000, 1.0000,
         1.0000],
        [0.9993, 1.0000, 1.0000, 1.0000, 0.9998, 0.9998, 1.0000, 0.9661, 0.5564,
         1.0000],
        [1.0000, 1.0000, 0.9999, 1.0000, 0.9785, 0.8706, 1.0000, 1.0000, 1.0000,
         0.5304]], grad_fn=<MaxBackward0>),
indices=tensor([[1, 2, 2, 2, 2, 0, 2, 1, 2, 1],
        [0, 2, 0, 0, 2, 1, 0, 0, 0, 0],
        [0, 0, 2, 1, 1, 1, 1, 0, 0, 0],
        [1, 2, 1, 2, 0, 1, 1, 1, 0, 0],
        [2, 0, 0, 1, 0, 2, 0, 1, 0, 1]]))

In [94]:
k.max(dim=-1)[1][0]

tensor([1, 2, 2, 2, 2, 0, 2, 1, 2, 1])

In [92]:
torch.arange(10).shape

torch.Size([10])

In [171]:
y

tensor([[1., 0., 0.]], grad_fn=<AddBackward0>)

In [107]:
l = nn.embedding(3, 4)

NameError: name 'nn' is not defined

In [172]:
class RewardModel(nn.Module):

    def __init__(self, model):
        super().__init__()
        self.embedding = model
        self.score = nn.Linear(model.embed_dim, 1, bias=False)

    def forward(self, x, seq_len=None):
        # x：表示文本，形状(B, T, C), seq_len：表示文本长度，形状(B)
        B, T = x.shape
        emb = self.embedding(x).last_hidden_state  # (B, T, C)
        ind = torch.arange(B, device=x.device)
        if seq_len == None:
            seq_len = torch.tensor([T] * B)
        # 获取最后一个词元的特征
        pooled_emb = emb[ind, seq_len - 1]         # (B,    C)
        score = self.score(pooled_emb)             # (B,    1)
        return score


r_model = RewardModel(GPT2Model.from_pretrained('gpt2'))

NameError: name 'nn' is not defined

In [175]:
x = torch.randn(1, 4, requires_grad=True)

In [176]:
torch.max(x)

tensor(1.7199, grad_fn=<MaxBackward1>)

In [181]:
logits = torch.randn(1, 5, requires_grad=True)
probs = F.softmax(logits, dim=-1)
y = torch.multinomial(probs, num_samples=1)
y

tensor([[1]])

In [182]:
y_one_hot = F.gumbel_softmax(logits, hard=True)
gumbel_y = torch.argmax(y_one_hot, dim=-1, keepdim=True)
y_one_hot

tensor([[1., 0., 0., 0., 0.]], grad_fn=<AddBackward0>)

In [183]:
gumbel_y

tensor([[0]])

In [189]:
def log(t, eps = 1e-20):
    return torch.log(t.clamp(min = eps))

def gumbel_noise(t):
    noise = torch.zeros_like(t).uniform_(0, 1)
    return -log(-log(noise))

def gumbel_sample(t, temperature = 1., dim = -1):
    return ((t / temperature) + gumbel_noise(t)).argmax(dim = dim)

In [190]:
gumbel_sample(torch.randn(1, 4, requires_grad=True))

tensor([2])

In [191]:
B, T, vs = (3, 4, 20)
logits = torch.randn(B, T, vs)
labels = torch.randint(vs, (B, T))

In [197]:
l = F.cross_entropy(logits.view(B * T, vs), labels.view(B * T), reduction='none')
l.mean(), F.cross_entropy(logits.view(B * T, vs), labels.view(B * T))

(tensor(3.9027), tensor(3.9027))

In [203]:
lnP = -F.cross_entropy(logits.transpose(-2, -1), labels, reduction='none')


tensor([[-4.3894, -4.6075, -2.8143, -3.5261],
        [-4.3982, -3.5565, -2.3154, -4.5414],
        [-4.1661, -3.0418, -2.9297, -6.5461]])

In [221]:
lossi = F.cross_entropy(logits.transpose(-2, -1), labels, reduction='none')

In [225]:
lossi.mean(-1).mean(-1)

tensor(3.9027)

In [ ]:
tokenizer

In [220]:
(-r * lnP).mean()

tensor(3.9027)

In [211]:
lnP.sum(-1)

tensor([-15.3374, -14.8116, -16.6836])

In [213]:
torch.randint(2, (20, 10))

tensor([[0, 0, 0, 0, 1, 1, 1, 0, 1, 1],
        [0, 0, 1, 0, 1, 1, 0, 0, 1, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 1, 0],
        [0, 1, 1, 1, 1, 1, 0, 0, 0, 1],
        [1, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 1, 1, 1, 0, 0],
        [0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
        [0, 1, 1, 1, 1, 1, 0, 0, 1, 0],
        [1, 1, 1, 1, 0, 0, 0, 0, 1, 1],
        [0, 1, 0, 1, 1, 1, 1, 1, 0, 1],
        [0, 1, 0, 0, 1, 1, 0, 1, 0, 1],
        [0, 0, 1, 1, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 0, 0, 0, 1, 0],
        [0, 1, 1, 0, 0, 1, 0, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
        [1, 0, 0, 1, 0, 0, 1, 0, 1, 1],
        [1, 1, 1, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 1, 0, 1, 1, 1, 1, 0, 0],
        [0, 0, 0, 1, 1, 1, 1, 1, 0, 1]])

In [2]:
import torch

In [23]:
a = torch.tensor([0.5, 0.2, 0.1])
r = torch.tensor([1001., 1002., 1003.])

In [28]:
a * r, (a * r).std()

(tensor([500.5000, 200.4000, 100.3000]), tensor(208.2627))

In [29]:
a * (r-1001), (a * (r-1001)).std()

(tensor([0.0000, 0.2000, 0.2000]), tensor(0.1155))

In [22]:
r-1001

tensor([0., 1., 2.])

In [34]:
(1000 * a).std()

tensor(208.1666)

In [35]:
(1 * a).std()

tensor(0.2082)

In [38]:
1000 * a + 1002 * a

tensor([1001.0000,  400.4000,  200.2000])

In [39]:
a + 2 * a

tensor([1.5000, 0.6000, 0.3000])

In [64]:
g = torch.normal(1, 1, (2, 20))
g.shape

torch.Size([2, 20])

In [78]:
r = torch.normal(1, 1, (2, 1))
r.shape

torch.Size([2, 1])

In [79]:
help(g * r)

tensor([[ 0.9881,  0.7762,  1.3812,  0.7958,  1.0094,  0.1070,  0.1709,  0.3961,
         -0.0118,  0.2604,  0.5242,  0.2400,  0.1989,  0.2737,  1.4879,  0.4091,
          0.7199, -0.2781,  0.7418,  1.2079],
        [ 3.4830,  0.1242,  0.8680,  0.0464,  0.8523,  1.0290, -0.3891,  2.5647,
         -0.1333,  3.3386,  0.1980,  0.2184,  0.4268,  4.9361,  3.0060,  1.3053,
          2.5407,  1.2318,  1.8263,  1.0207]])

In [86]:
help(g.norm)

Help on method norm in module torch._tensor:

norm(p: Union[float, str, NoneType] = 'fro', dim=None, keepdim=False, dtype=None) method of torch.Tensor instance
    See :func:`torch.norm`



In [59]:
(g * rr).std()

tensor(1.4053)

In [88]:
(g**2).sum(dim=-1)

tensor([39.9750, 37.7648])

In [179]:
def norm_(g):
    k = g / g.norm(dim=-1, keepdim=True)
    return k

In [1]:
import torch

In [2]:
num = 10000
grad = torch.normal(0, 1, (num, 100))
g = torch.normal(100, 1, (num, 1))
(grad * g).std()

tensor(99.9496)

In [3]:
num = 10000
grad = torch.normal(0, 1, (num, 100))
g = torch.normal(100, 1, (num, 1)) - 100
(grad * g).std()

tensor(1.0004)

In [261]:
(g * r).mean(-1).std()

tensor(0.0996)

In [241]:
torch.normal(100, 0, (10, 1))

tensor([[100.],
        [100.],
        [100.],
        [100.],
        [100.],
        [100.],
        [100.],
        [100.],
        [100.],
        [100.]])