In [ ]:
from torch.nn.utils.rnn import pad_sequence
import torch

a = torch.ones(2, 10)
b = torch.ones(1, 10)
c = torch.ones(4, 10)
d = pad_sequence([a, b, c])

In [ ]:
d.size()

In [ ]:
d[:,1]

In [ ]:
a

In [ ]:
b

In [ ]:
c

In [ ]:
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence
seq = torch.tensor([[1, 2, 0], [3, 0, 0], [4, 5, 6]])
lens = [2, 1, 3]
packed = pack_padded_sequence(seq, lens, batch_first=True, enforce_sorted=False)
packed
seq_unpacked, lens_unpacked = pad_packed_sequence(packed, batch_first=True)
seq_unpacked
lens_unpacked

In [ ]:
seq, lens, packed

In [ ]:
seq_unpacked

In [ ]:
from datasets import load_dataset # huggingface datasets

In [ ]:
dataset = load_dataset("stas/openwebtext-10k")

In [ ]:
dataset

In [ ]:
dataset["train"][1]

In [ ]:
dir(dataset["train"].map)

In [ ]:
import torch.nn as nn

conv1 = nn.Conv2d(3, 4, kernel_size=3, 
                               stride=4, padding=1, bias=False)
conv2 = nn.Conv2d(3, 4, kernel_size=1, 
                               stride=4, padding=0, bias=False)

In [ ]:
conv1(torch.randn(1, 3, 10, 10)).size()

In [ ]:
conv2(torch.randn(1, 3, 10, 10)).size()

In [ ]:
import torch.nn.functional as F
import torch

logits = torch.tensor([[0.5, 0.5], [0.5, 0.5]])
logits.shape

In [ ]:
F.cross_entropy(logits, torch.tensor([0, -100]), reduction='sum')

In [ ]:
from transformers import AutoTokenizer
import matplotlib.pyplot as plt
%matplotlib inline


tokenizer_gpt2 = AutoTokenizer.from_pretrained('gpt2')

In [ ]:
tokenizer_gpt2.pretrained_vocab_files_map

In [ ]:
tokenizer_gpt2.is_fast

In [ ]:
tokenizer_gpt2.get_vocab()

In [ ]:
len(tokenizer_gpt2.get_added_vocab())

In [ ]:
from datasets import load_dataset

raw_data = load_dataset('BelleGroup/train_0.5M_CN')

def get_training_corpus():
    # 为了减少运算时间，只选择较少的训练数据
    data = raw_data["train"].select(range(1000))
    for idx in range(0, len(data), 1000):
        samples = data[idx : idx + 1000]
        yield samples.get('instruction', []) + samples.get('output', [])

In [ ]:
tokenizer_zh = tokenizer_gpt2.train_new_from_iterator(get_training_corpus(), 330)

In [ ]:
len(tokenizer_zh.get_vocab())

In [ ]:
tokenizer_zh.get_vocab()

In [1]:
from datasets import load_dataset

# This can take a few minutes to load, so grab a coffee or tea while you wait!
raw_datasets = load_dataset("code_search_net", "python")

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Extracting data files:   0%|          | 0/3 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/412178 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/22176 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/23107 [00:00<?, ? examples/s]

In [3]:
data = raw_datasets["train"].select(range(10000))

In [4]:
data

Dataset({
    features: ['repository_name', 'func_path_in_repository', 'func_name', 'whole_func_string', 'language', 'func_code_string', 'func_code_tokens', 'func_documentation_string', 'func_documentation_tokens', 'split_name', 'func_code_url'],
    num_rows: 10000
})

In [7]:
print(data[1]['whole_func_string'])

def setparents(self):
        """Correct all parent relations for elements within the scop. There is sually no need to call this directly, invoked implicitly by :meth:`copy`"""
        for c in self:
            if isinstance(c, AbstractElement):
                c.parent = self
                c.setparents()


In [13]:
len(data['func_code_string'])

10000

In [14]:
chars = sorted(list(set(''.join(data['func_code_string']))))

In [17]:
chars

['\t',
 '\n',
 '\r',
 ' ',
 '!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '{',
 '|',
 '}',
 '~',
 '\xa0',
 '°',
 '±',
 '²',
 '³',
 '·',
 '¸',
 'º',
 'É',
 '×',
 'Ø',
 'á',
 'â',
 'ã',
 'ä',
 'ç',
 'é',
 'ê',
 'í',
 'ó',
 'õ',
 'ö',
 'Δ',
 'Ω',
 'δ',
 'ε',
 'λ',
 'μ',
 'π',
 'ρ',
 'σ',
 'τ',
 'Б',
 'И',
 'а',
 'б',
 'в',
 'д',
 'ж',
 'к',
 'н',
 'о',
 'п',
 'р',
 'с',
 'т',
 'у',
 'ы',
 'я',
 '‐',
 '–',
 '‘',
 '’',
 '“',
 '”',
 '⁶',
 '→',
 '↦',
 '⇒',
 '∂',
 '∈',
 '−',
 '∗',
 '≤',
 '≥',
 '⌟',
 '─',
 '│

In [30]:
char2ind = {s : i + 1 for i, s in enumerate(chars)}
char2ind['<|endoftext|>'] = 0

In [31]:
char2ind

{'\t': 1,
 '\n': 2,
 '\r': 3,
 ' ': 4,
 '!': 5,
 '"': 6,
 '#': 7,
 '$': 8,
 '%': 9,
 '&': 10,
 "'": 11,
 '(': 12,
 ')': 13,
 '*': 14,
 '+': 15,
 ',': 16,
 '-': 17,
 '.': 18,
 '/': 19,
 '0': 20,
 '1': 21,
 '2': 22,
 '3': 23,
 '4': 24,
 '5': 25,
 '6': 26,
 '7': 27,
 '8': 28,
 '9': 29,
 ':': 30,
 ';': 31,
 '<': 32,
 '=': 33,
 '>': 34,
 '?': 35,
 '@': 36,
 'A': 37,
 'B': 38,
 'C': 39,
 'D': 40,
 'E': 41,
 'F': 42,
 'G': 43,
 'H': 44,
 'I': 45,
 'J': 46,
 'K': 47,
 'L': 48,
 'M': 49,
 'N': 50,
 'O': 51,
 'P': 52,
 'Q': 53,
 'R': 54,
 'S': 55,
 'T': 56,
 'U': 57,
 'V': 58,
 'W': 59,
 'X': 60,
 'Y': 61,
 'Z': 62,
 '[': 63,
 '\\': 64,
 ']': 65,
 '^': 66,
 '_': 67,
 '`': 68,
 'a': 69,
 'b': 70,
 'c': 71,
 'd': 72,
 'e': 73,
 'f': 74,
 'g': 75,
 'h': 76,
 'i': 77,
 'j': 78,
 'k': 79,
 'l': 80,
 'm': 81,
 'n': 82,
 'o': 83,
 'p': 84,
 'q': 85,
 'r': 86,
 's': 87,
 't': 88,
 'u': 89,
 'v': 90,
 'w': 91,
 'x': 92,
 'y': 93,
 'z': 94,
 '{': 95,
 '|': 96,
 '}': 97,
 '~': 98,
 '\xa0': 99,
 '°': 100,
 

In [32]:
ind2char = {i : s for s, i in char2ind.items()}
ind2char

{1: '\t',
 2: '\n',
 3: '\r',
 4: ' ',
 5: '!',
 6: '"',
 7: '#',
 8: '$',
 9: '%',
 10: '&',
 11: "'",
 12: '(',
 13: ')',
 14: '*',
 15: '+',
 16: ',',
 17: '-',
 18: '.',
 19: '/',
 20: '0',
 21: '1',
 22: '2',
 23: '3',
 24: '4',
 25: '5',
 26: '6',
 27: '7',
 28: '8',
 29: '9',
 30: ':',
 31: ';',
 32: '<',
 33: '=',
 34: '>',
 35: '?',
 36: '@',
 37: 'A',
 38: 'B',
 39: 'C',
 40: 'D',
 41: 'E',
 42: 'F',
 43: 'G',
 44: 'H',
 45: 'I',
 46: 'J',
 47: 'K',
 48: 'L',
 49: 'M',
 50: 'N',
 51: 'O',
 52: 'P',
 53: 'Q',
 54: 'R',
 55: 'S',
 56: 'T',
 57: 'U',
 58: 'V',
 59: 'W',
 60: 'X',
 61: 'Y',
 62: 'Z',
 63: '[',
 64: '\\',
 65: ']',
 66: '^',
 67: '_',
 68: '`',
 69: 'a',
 70: 'b',
 71: 'c',
 72: 'd',
 73: 'e',
 74: 'f',
 75: 'g',
 76: 'h',
 77: 'i',
 78: 'j',
 79: 'k',
 80: 'l',
 81: 'm',
 82: 'n',
 83: 'o',
 84: 'p',
 85: 'q',
 86: 'r',
 87: 's',
 88: 't',
 89: 'u',
 90: 'v',
 91: 'w',
 92: 'x',
 93: 'y',
 94: 'z',
 95: '{',
 96: '|',
 97: '}',
 98: '~',
 99: '\xa0',
 100: '°',
 

In [ ]:
block_size = 8

def build_dataset(words):  
    X, Y = [], []
    for w in words:
        context = [0] * block_size
        for ch in w + '.':
            ix = stoi[ch]
            X.append(context)
            Y.append(ix)
            context = context[1:] + [ix] # crop and append

        

In [38]:
import torch

embedding = torch.randn(10, 4)

In [39]:
embedding

tensor([[-1.0708,  0.3567, -0.3461, -0.3142],
        [-1.4380, -0.2864, -1.0363,  0.4179],
        [-0.3336, -0.1104, -0.3592,  1.9704],
        [ 0.3901,  0.2693,  0.4197,  1.0691],
        [-2.5862, -0.9876,  2.0897, -0.7323],
        [-0.6693,  1.3959,  1.3124, -0.7408],
        [ 0.8491,  0.1856, -0.7332, -0.0313],
        [ 0.9752,  0.0266,  0.9608, -1.0253],
        [-0.1048, -1.6725, -0.1999, -0.2459],
        [-0.3935, -0.9368,  0.4273,  0.7951]])

In [42]:
embedding[torch.tensor([1, 3, 4])]

tensor([[-1.4380, -0.2864, -1.0363,  0.4179],
        [ 0.3901,  0.2693,  0.4197,  1.0691],
        [-2.5862, -0.9876,  2.0897, -0.7323]])

In [51]:
import torch.nn.functional as F

x = F.one_hot(torch.tensor([1]), num_classes=10).float()

In [52]:
x @ embedding

tensor([[-1.4380, -0.2864, -1.0363,  0.4179]])

In [53]:
from datasets import Dataset
dataset = Dataset.from_dict({"a": [0, 1, 2]})
dataset_with_duplicates = dataset.map(lambda batch: {"b": batch["a"] * 2}, remove_columns=["a"], batched=True)
len(dataset_with_duplicates)

Map:   0%|          | 0/3 [00:00<?, ? examples/s]

6

In [54]:
dataset

Dataset({
    features: ['a'],
    num_rows: 3
})

In [55]:
dataset_with_duplicates

Dataset({
    features: ['b'],
    num_rows: 6
})

In [91]:
from datasets import Dataset

d = Dataset.from_dict({"foo": [[[1, 2, 3], [5, 7, 8]]], 'y': [[8, 9]]})
b = d.map(lambda x: {'t': [i for row in x["foo"] for i in row], 'yy':  [i for row in x["y"] for i in row]}, batched=True, remove_columns=['foo', 'y'])
#nb = d.map(lambda x: {"foo": [i for row in x["foo"] for i in row]})


print(d["foo"])
# [1, 2, 3, 5, 7, 8]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

[[[1, 2, 3], [5, 7, 8]]]


In [94]:
b['t'], b['yy']

([[1, 2, 3], [5, 7, 8]], [8, 9])

In [93]:
b

Dataset({
    features: ['t', 'yy'],
    num_rows: 2
})

In [90]:
d

Dataset({
    features: ['foo', 'y'],
    num_rows: 1
})

In [98]:
def f(x):
    return [i for row in x for i in row]

In [99]:
f([[[1, 2, 3], [5, 7, 8]]])

[[1, 2, 3], [5, 7, 8]]

In [101]:
import torch.nn as nn

l = nn.Linear(10, 20)

In [107]:
l.to('cpu')

Linear(in_features=10, out_features=20, bias=True)

In [119]:
rnn = nn.RNN(10, 20)
input = torch.randn(5, 3, 10)

In [120]:
h0 = torch.randn(2, 3, 20)
output, hn = rnn(input)

In [123]:
output[-1]

tensor([[-0.6609,  0.0288,  0.4044, -0.0861,  0.1431, -0.8551,  0.3041, -0.5963,
         -0.2678, -0.7192, -0.3108, -0.4540,  0.0777,  0.3821,  0.4365,  0.1742,
         -0.0074, -0.5784, -0.6424, -0.0823],
        [ 0.6820,  0.0065,  0.8082, -0.0289,  0.5228, -0.7669, -0.4600,  0.2061,
         -0.3060,  0.2323, -0.3815,  0.1412, -0.3332,  0.4825, -0.5178, -0.1881,
         -0.1866, -0.4605, -0.6267,  0.0444],
        [ 0.3235,  0.3109,  0.2414, -0.1143, -0.6785,  0.3351,  0.7283, -0.7975,
         -0.5947, -0.5497,  0.3621, -0.2100,  0.1001, -0.7177,  0.2893,  0.4918,
         -0.3884, -0.2158, -0.3640,  0.1690]], grad_fn=<SelectBackward0>)

In [125]:
hn == output[-1]

tensor([[[True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True]]])

In [ ]:


from datasets import load_dataset

raw_datasets = load_dataset("code_search_net", "python")
datasets = raw_datasets["train"].select(range(1000))
# 通过索引提取datasets数据的时候，返回一个dict，其中的value是一个字符串
print(datasets[8]['whole_func_string'])
# 当传入的是一个数组时，返回的依然是一个dict，但其中的value是一个列表
print(datasets[8: 10]['whole_func_string'])




In [126]:
rnn = nn.RNN(1, 2)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
output, hn = rnn(input, h0)

In [220]:
rnn = nn.RNN(3, 2, nonlinearity='tanh', batch_first=True)

In [266]:
k = list(rnn.parameters())
k

[Parameter containing:
 tensor([[-0.4865, -0.6551, -0.0722],
         [ 0.0173,  0.3202, -0.1966]], requires_grad=True),
 Parameter containing:
 tensor([[ 0.1778,  0.4318],
         [ 0.6170, -0.1327]], requires_grad=True),
 Parameter containing:
 tensor([0.2245, 0.3032], requires_grad=True),
 Parameter containing:
 tensor([-0.7008,  0.3266], requires_grad=True)]

In [267]:
h0 = torch.randn(1, 1, 2)
h0.shape

torch.Size([1, 1, 2])

In [268]:
x = torch.randn(1, 3, 3)
x.shape

torch.Size([1, 3, 3])

In [269]:
o, h = rnn(x, h0)
print(o, h)
o.shape, h.shape

tensor([[[-0.9349,  0.8853],
         [ 0.5682, -0.1969],
         [ 0.6334,  0.5003]]], grad_fn=<TransposeBackward1>) tensor([[[0.6334, 0.5003]]], grad_fn=<StackBackward0>)


(torch.Size([1, 3, 2]), torch.Size([1, 1, 2]))

In [225]:
print(x @ k[0].T + k[2] + k[3] + h0 @ k[1].T)
F.tanh(x @ k[0].T + k[2] + k[3] + h0 @ k[1].T)

tensor([[[-1.0624,  0.3718],
         [-2.3894,  0.3730],
         [ 1.3751,  0.0979]]], grad_fn=<AddBackward0>)


tensor([[[-0.7866,  0.3556],
         [-0.9833,  0.3566],
         [ 0.8798,  0.0976]]], grad_fn=<TanhBackward0>)

In [270]:
class RNN(nn.Module):

    def __init__(self, input_size, hidden_size):
        super().__init__()
        self.hidden_size = hidden_size
        self.i2h = nn.Linear(input_size + hidden_size, hidden_size)
    
    def forward(self, x, hidden=None):
        re = []
        # B batch_size,
        # T sequence length,
        # C number of channels.
        B, T, C = x.shape
        x = x.transpose(0, 1) # (T, B, C)
        seq_len = x.shape[0]
        if hidden is None:
            hidden = self.init_hidden(B)
        for i in range(seq_len):
            # x[i]: (B, C); hidden: (B, hidden_size)
            combined = torch.cat((x[i], hidden), dim=1)
            hidden = F.relu(self.i2h(combined))  # (B, hidden_size)
            re.append(hidden)
        result_tensor = torch.stack(re, 0)  # (T, B, hidden_size)
        return result_tensor.transpose(0, 1)
    
    def init_hidden(self, B):
        return torch.zeros(B, self.hidden_size)

In [307]:
rnn = nn.RNN(3, 2, nonlinearity='relu', batch_first=True)
h0 = torch.randn(1, 1, 2)
x = torch.randn(1, 3, 3)
o, h = rnn(x, h0)
print(o, o.shape)

tensor([[[0.5772, 0.0000],
         [1.0884, 0.2372],
         [0.0000, 0.2318]]], grad_fn=<TransposeBackward1>) torch.Size([1, 3, 2])


In [308]:
m = RNN(3, 2)
k = list(rnn.parameters())
m.i2h.weight = nn.Parameter(torch.cat((k[0], k[1]), dim=1))
m.i2h.bias = nn.Parameter(k[2] + k[3])

In [309]:
o = m(x, h0.squeeze(0))
print(o, o.shape)

tensor([[[0.5772, 0.0000],
         [1.0884, 0.2372],
         [0.0000, 0.2318]]], grad_fn=<TransposeBackward0>) torch.Size([1, 3, 2])


In [312]:
ds = load_dataset("codeparrot/github-code", "Python-all", streaming=True, split="train")


In [315]:
d = ds.filter(lambda x: x['repo_name'] == 'pytorch/pytorch')

In [344]:
rawdata = load_dataset('codeparrot/github-code', languages=["Python"], licenses=['bsd-3-clause'],
                       streaming=True, split='train')

In [352]:
next(iter(rawdata))

{'code': '# The purpose of these tests are to ensure that calling ufuncs with quantities\n# returns quantities with the right units, or raises exceptions.\n\nimport warnings\n\nimport pytest\nimport numpy as np\nfrom numpy.testing.utils import assert_allclose\n\nfrom ... import units as u\nfrom ...tests.helper import raises\nfrom ...extern.six.moves import zip\nfrom ...utils.compat import NUMPY_LT_1_13\n\n\nclass TestUfuncCoverage(object):\n    """Test that we cover all ufunc\'s"""\n\n    def test_coverage(self):\n        all_np_ufuncs = set([ufunc for ufunc in np.core.umath.__dict__.values()\n                             if type(ufunc) == np.ufunc])\n\n        from .. import quantity_helper as qh\n\n        all_q_ufuncs = (qh.UNSUPPORTED_UFUNCS |\n                        set(qh.UFUNC_HELPERS.keys()))\n\n        assert all_np_ufuncs - all_q_ufuncs == set([])\n        assert all_q_ufuncs - all_np_ufuncs == set([])\n\n\nclass TestQuantityTrigonometricFuncs(object):\n    """\n    Test tri

In [336]:
raw_datasets = load_dataset("code_search_net", "python")
raw_datasets['train'][10]

{'repository_name': 'proycon/pynlpl',
 'func_path_in_repository': 'pynlpl/formats/folia.py',
 'func_name': 'AbstractElement.findreplaceables',
 'whole_func_string': 'def findreplaceables(Class, parent, set=None,**kwargs):\n        """Internal method to find replaceable elements. Auxiliary function used by :meth:`AbstractElement.replace`. Can be overriden for more fine-grained control."""\n        return list(parent.select(Class,set,False))',
 'language': 'python',
 'func_code_string': 'def findreplaceables(Class, parent, set=None,**kwargs):\n        """Internal method to find replaceable elements. Auxiliary function used by :meth:`AbstractElement.replace`. Can be overriden for more fine-grained control."""\n        return list(parent.select(Class,set,False))',
 'func_code_tokens': ['def',
  'findreplaceables',
  '(',
  'Class',
  ',',
  'parent',
  ',',
  'set',
  '=',
  'None',
  ',',
  '*',
  '*',
  'kwargs',
  ')',
  ':',
  'return',
  'list',
  '(',
  'parent',
  '.',
  'select',
 

In [359]:
l = raw_datasets['train'].filter(lambda x: 'apache/spark' in x['repository_name'])

Filter:   0%|          | 0/412178 [00:00<?, ? examples/s]

In [363]:
set(l['repository_name'])

{'apache/spark'}

In [361]:
l[100]

{'repository_name': 'apache/spark',
 'func_path_in_repository': 'python/pyspark/rdd.py',
 'func_name': 'RDD.lookup',
 'whole_func_string': 'def lookup(self, key):\n        """\n        Return the list of values in the RDD for key `key`. This operation\n        is done efficiently if the RDD has a known partitioner by only\n        searching the partition that the key maps to.\n\n        >>> l = range(1000)\n        >>> rdd = sc.parallelize(zip(l, l), 10)\n        >>> rdd.lookup(42)  # slow\n        [42]\n        >>> sorted = rdd.sortByKey()\n        >>> sorted.lookup(42)  # fast\n        [42]\n        >>> sorted.lookup(1024)\n        []\n        >>> rdd2 = sc.parallelize([((\'a\', \'b\'), \'c\')]).groupByKey()\n        >>> list(rdd2.lookup((\'a\', \'b\'))[0])\n        [\'c\']\n        """\n        values = self.filter(lambda kv: kv[0] == key).values()\n\n        if self.partitioner is not None:\n            return self.ctx.runJob(values, lambda x: x, [self.partitioner(key)])\n\n       

In [367]:
x = torch.randn(10, 40)

In [368]:
x[:, -10:].shape

torch.Size([10, 10])

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class RNNCell(nn.Module):

    def __init__(self, input_size, hidden_size):
        super().__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        combined_size = self.input_size + self.hidden_size
        self.i2h = nn.Linear(combined_size, self.hidden_size)

    def forward(self, inputs, hidden=None):
        if hidden is None:
            hidden = self.init_hidden(inputs.device)   # (1,     H)
        # inputs: (1, I)
        combined = torch.cat((inputs, hidden), dim=1)  # (1, I + H)
        hidden = F.relu(self.i2h(combined))            # (1,     H)
        return hidden

    def init_hidden(self, device):
        return torch.zeros((1, self.hidden_size), device=device)


r_model = RNNCell(2, 1)
h = None
hidden = []
inputs = torch.randn(3, 1, 2)
for i in range(3):
    h = r_model(inputs[i], h)
    hidden.append(h)


In [14]:
import torch

f_outputs = torch.randn(10, 2, 3)
b_outputs = torch.randn(10, 2, 3)

l = [torch.cat((f, b), -1) for f, b in zip(
        f_outputs, reversed(b_outputs))]

In [19]:
for f, b in zip(f_outputs, reversed(b_outputs)):
    print(f.shape, b.shape)

torch.Size([2, 3]) torch.Size([2, 3])
torch.Size([2, 3]) torch.Size([2, 3])
torch.Size([2, 3]) torch.Size([2, 3])
torch.Size([2, 3]) torch.Size([2, 3])
torch.Size([2, 3]) torch.Size([2, 3])
torch.Size([2, 3]) torch.Size([2, 3])
torch.Size([2, 3]) torch.Size([2, 3])
torch.Size([2, 3]) torch.Size([2, 3])
torch.Size([2, 3]) torch.Size([2, 3])
torch.Size([2, 3]) torch.Size([2, 3])


In [26]:
f.shape, b.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [52]:
f_rnn = nn.RNN(3, 6, batch_first=True)
b_rnn = nn.RNN(3, 6, batch_first=True)

x = torch.randn(4, 10, 3)           # (B, T, C)
f = f_rnn(x)[0]  # (B, T, H)
b = b_rnn(reversed(x))[0]  # (B, T, H)
o = torch.cat((f, reversed(b)), dim=-1)
o.shape

torch.Size([4, 10, 12])

In [37]:
f_rnn = nn.RNN(3, 5, batch_first=True)
x = torch.randn(4, 10, 3)           # (B, T, C)


In [44]:
f.shape, b.shape

(torch.Size([4, 10, 5]), torch.Size([4, 10, 5]))

In [47]:
torch.cat((f, b), dim=-1).shape

torch.Size([4, 10, 12])

In [59]:
encoder = nn.RNN(3, 6, batch_first=True)
decoder = nn.RNN(3, 6, batch_first=True)
h2o = nn.Linear(H, VS)

x = torch.randn(4, 10, 3)   # (B, T, C)
e = encoder(x)[0]           # (B, T, H)
c = e[:, -1, :].unsqueeze(0)             # (B,    H)
y = init
while y != <|e|>:
    c = decoder(y, c)
    y = c.out

torch.Size([1, 4, 6])


torch.Size([4, 1, 6])

In [60]:
class RNN(nn.Module):

    def __init__(self, input_size, hidden_size):
        super().__init__()
        self.hidden_size = hidden_size
        self.i2h = nn.Linear(input_size + hidden_size, hidden_size)

    def forward(self, x, hidden=None):
        re = []
        # B batch_size,
        # T sequence length,
        # C number of channels.
        B, T, C = x.shape
        x = x.transpose(0, 1) # (T, B, C)
        seq_len = x.shape[0]
        if hidden is None:
            hidden = self.init_hidden(B, x.device)
        for i in range(seq_len):
            # x[i]: (B, C); hidden: (B, H)
            combined = torch.cat((x[i], hidden), dim=1)
            hidden = F.relu(self.i2h(combined))  # (   B, H)
            re.append(hidden)
        result_tensor = torch.stack(re, dim=0)   # (T, B, H)
        return result_tensor.transpose(0, 1)     # (B, T, H)

    def init_hidden(self, B, device):
        return torch.zeros((B, self.hidden_size), device=device)


In [68]:
encoder = RNN(4, 6)
decoder = RNN(4, 6)
h2i = nn.Linear(6, 4)


x = torch.randn(5, 9, 4)                      # (B, T, C)
e = encoder(x)          # (B, T, H)
c = e[:, -1, :]         # (B,    H)
y = torch.randn(5, 1, 4) # (B, 1, C)
ix = ''
while ix != '<|e|>':
    h = decoder(y, c)[:, -1, :]   # (B, H)
    #prob = F.softmax(h2o(h), dim=-1)  # (B, VS)
    #ix = torch.multinomial(prob, num_samples=1)
    ix = h2i(h).unsqueeze(1)
    print(ix.shape)
    y = torch.cat((y, ix), dim=1)
    print(y.shape)
    tttt


torch.Size([5, 1, 4])
torch.Size([5, 2, 4])


NameError: name 'tttt' is not defined