In [1]:
# 安装PyTorch
!pip install torch

In [2]:
import torch

# 创建tensor
## 使用tensor封装的函数创建tensor
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1024)
random = torch.rand(3, 4)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8090, 0.7935, 0.2099, 0.9279],
        [0.8136, 0.7422, 0.4769, 0.4955],
        [0.3602, 0.1178, 0.7852, 0.0228]])


In [3]:
# 创建tensor
## 从Python对象创建
data = [[2, 3, 4], [1, 0, 1]]
t_data = torch.tensor(data)
print(t_data)

## 从Numpy对象创建
import numpy as np

n_data = np.array(data)
tn_data = torch.from_numpy(n_data)
print(tn_data)

## Numpy bridge，也就是对numpy对象的改变会传导到tensor
n_data += 1
torch.all(torch.from_numpy(n_data) == tn_data)

tensor([[2, 3, 4],
        [1, 0, 1]])
tensor([[2, 3, 4],
        [1, 0, 1]])


tensor(True)

In [4]:
# 变换tensor维度

## 增加或减少数据的维度
a = torch.rand(3, 4)
print(a.shape)
## 增加维度
b = a.unsqueeze(0)
print(b.shape)
## 减少维度
c = b.squeeze(0)
print(c.shape)
## 数据相同，但是维度不同
print(torch.all(c.eq(b)))
print(c.shape == b.shape)

torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([3, 4])
tensor(True)
False


In [5]:
# 变换tensor形状
data = torch.tensor(range(0, 10))
print(data, data.shape)
view1 = data.view(2, 5)
print(view1)
transpose1 = view1.T
print(transpose1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([10])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])


In [6]:
## 非毗邻存储（contiguous）的对象不能进行view操作
print(view1.is_contiguous(), transpose1.is_contiguous())
view2 = transpose1.view(1, 10)

True False


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [7]:
# 逐元素操作（element-wise operations）
twos = torch.ones(2, 2) * 2
print(twos)

powers = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers)

tensor([[2., 2.],
        [2., 2.]])
tensor([[ 2.,  4.],
        [ 8., 16.]])


In [8]:
## tensor广播，tensor broadcasting
a = torch.tensor(range(1, 7)).view(2, 3)
b = torch.tensor(range(1, 4)).view(   3)
print(a)
print(b)
print(a * b)

## 关于广播，更复杂的例子
a =     torch.ones(4, 1, 3, 2)
b = a * torch.rand(   5, 1, 2)
print(b.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3])
tensor([[ 1,  4,  9],
        [ 4, 10, 18]])
torch.Size([4, 5, 3, 2])


In [9]:
# 矩阵运算
mat1 = torch.randn(3, 4)
mat2 = torch.randn(4, 5)
re = mat1 @ mat2
print(re.shape)
## 矩阵运算的广播
mat1 = torch.randn(5, 1, 3, 4)
mat2 = torch.randn(   8, 4, 5)
re = mat1 @ mat2
print(re.shape)

torch.Size([3, 5])
torch.Size([5, 8, 3, 5])


In [10]:
# 向量运算
# vector x vector
vec1 = torch.randn(3)
vec2 = torch.randn(3)
print((vec1 @ vec2).shape)
# matrix x vector
mat = torch.randn(3, 4)
vec = torch.randn(4)
print((mat @ vec).shape)
# batched matrix x broadcasted vector
mat = torch.randn(10, 3, 4)
vec = torch.randn(4)
print((mat @ vec).shape)

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
