In [1]:
# Install third-party libraries
!pip install torch

/bin/bash: /usr/local/bin/pip: /usr/local/opt/python/bin/python3.6: bad interpreter: No such file or directory


In [2]:
import torch

# Create tensors
## Create tensors with convenience functions
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1024)
random = torch.rand(3, 4)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8090, 0.7935, 0.2099, 0.9279],
        [0.8136, 0.7422, 0.4769, 0.4955],
        [0.3602, 0.1178, 0.7852, 0.0228]])


In [3]:
# Create tensors
## Create from Python objects
data = [[2, 3, 4], [1, 0, 1]]
t_data = torch.tensor(data)
print(t_data)

## Create from NumPy objects
import numpy as np

n_data = np.array(data)
tn_data = torch.from_numpy(n_data)
print(tn_data)

## NumPy bridge: changes to a NumPy object propagate to the tensor
n_data += 1
torch.all(torch.from_numpy(n_data) == tn_data)

tensor([[2, 3, 4],
        [1, 0, 1]])
tensor([[2, 3, 4],
        [1, 0, 1]])


tensor(True)

In [4]:
# Change tensor dimensions
## Increase or decrease the number of dimensions
a = torch.rand(3, 4)
print(a.shape)
## Increase dimensions
b = a.unsqueeze(0)
print(b.shape)
## Decrease dimensions
c = b.squeeze(0)
print(c.shape)
## Same data, different dimensions
print(torch.all(c.eq(b)))
print(c.shape == b.shape)

torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([3, 4])
tensor(True)
False


In [5]:
# Reshape tensors
data = torch.tensor(range(0, 10))
print(data, data.shape)
view1 = data.view(2, 5)
print(view1)
transpose1 = view1.T
print(transpose1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([10])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])


In [6]:
## Non-contiguous objects cannot use the view operation
print(view1.is_contiguous(), transpose1.is_contiguous())
view2 = transpose1.view(1, 10)

True False


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [7]:
# Element-wise operations
twos = torch.ones(2, 2) * 2
print(twos)

powers = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers)

tensor([[2., 2.],
        [2., 2.]])
tensor([[ 2.,  4.],
        [ 8., 16.]])


In [8]:
## Tensor broadcasting
a = torch.tensor(range(1, 7)).view(2, 3)
b = torch.tensor(range(1, 4)).view(   3)
print(a)
print(b)
print(a * b)

## A more complex broadcasting example
a =     torch.ones(4, 1, 3, 2)
b = a * torch.rand(   5, 1, 2)
print(b.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3])
tensor([[ 1,  4,  9],
        [ 4, 10, 18]])
torch.Size([4, 5, 3, 2])


In [9]:
# Matrix operations
mat1 = torch.randn(3, 4)
mat2 = torch.randn(4, 5)
re = mat1 @ mat2
print(re.shape)
## Broadcasting in matrix operations
mat1 = torch.randn(5, 1, 3, 4)
mat2 = torch.randn(   8, 4, 5)
re = mat1 @ mat2
print(re.shape)

torch.Size([3, 5])
torch.Size([5, 8, 3, 5])


In [10]:
# Vector operations
# Vector and vector
vec1 = torch.randn(3)
vec2 = torch.randn(3)
print((vec1 @ vec2).shape)
# Matrix and vector
mat = torch.randn(3, 4)
vec = torch.randn(4)
print((mat @ vec).shape)
# Tensor and vector
mat = torch.randn(10, 3, 4)
vec = torch.randn(4)
print((mat @ vec).shape)

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
